### ISSUE TITLE
# FEATURE Building a `Search Portal` as a single centralized location where students can view shared files of any teacher of any department.

### ISSUE THREAD

**Issue by AlexiusTatius** [AlexiusTatius/NITJ_Intranet_Culture#35]
The `Search Portal` would contain 2 drop down menus:
1. Department Name. 
2. Teacher Name.

Each Department would contain the names of the respective teachers.  Here's an image to illustrate the frontend:

![Search Portal](https://github.com/user-attachments/assets/689e03ba-9645-4d7a-b453-799c520cb96d)

We'd also implement a feature where you can type in the department or the teacher name and it will search through the available options and give us the matching result.

Suggestions for building the backend are welcomed in this issue comments or in the slack channel.

Also, I've talked with sir, he's asking to KEEP ALL the previous generation links methods. So we won't change the previous logic. Just add the new features

**Comment by chahatkesh** [comment]
Issue Resolved in PR : #38
